### ISSUE TITLE
Value not changing

### ISSUE THREAD

**Issue by sigalabs** [RobinSi/ADConverter#1]
Hello,
i am trying to use your library with a PmodA5 device.

The chip inits but i can't read a real value, i am only reading the same raw value whatever i am trying...

Is the example provided with the library works out of the box with a PmodA5 device? Do i need to do any special pin configuration etc?

Thank you for your great work,

Kostas

**Comment by sigalabs** [comment]
OK it seems there is a problem with the register that sets the internal clock. It is not working so the external clock is selected by default. (The board has no crystal soldered).

**Comment by t0311** [comment]
Hi sigalabs,

Can I ask if there's a solution to this problem?
